export const translations = {
  en: {
    specialKicker: 'A LITTLE EXTRA TEMPTATION', specialHeading: 'This week’s specials.', specialNote: 'Sample offers — prices, pack sizes and dates await confirmation.', specialBadge: 'SAMPLE SPECIAL · TO BE CONFIRMED', specialEnquire: 'Enquire on WhatsApp ↗', specialMessage: 'Hi Stofpad Biltong! I’d like to enquire about this sample special:', specialConfirm: 'Please confirm the offer price, pack size, validity dates and availability.',
    nav: 'Main navigation', products: 'Our products', how: 'How to order', order: 'Your order',
    eyebrow: 'BIG FLAVOUR. NO FUSS.', hero: 'A proper biltong moment.', intro: 'A little for the road. A board to share. Choose your favourites and let Stofpad Biltong take it from there on WhatsApp.', browse: 'Explore the products ↗', note: 'Browse here. Order with a real person.',
    good: 'THE GOOD STUFF', catalogue: 'Our biltong & products.', catalogueIntro: 'Pick your weight and preparation. Add your favourites to one order.', allCount: 'products', filter: 'Filter products by category', swipe: 'Swipe to browse →', size: 'Weight / pack size', preparation: 'Preparation', add: 'Add to order', pending: 'Price to be confirmed', estimate: 'Estimated price', added: 'Added to your order.', limit: 'You can add up to 99 of the same selection.',
    orderHeading: 'Your favourites, together.', empty: 'Your order is empty. Add something you fancy from the catalogue.', remove: 'Remove', quantity: 'Quantity', courier: 'Add The Courier Guy delivery — R175', deliveryNote: 'Courier eligibility and the final delivery charge will be confirmed by Stofpad Biltong.', total: 'Estimated total', known: 'Known subtotal', excludes: 'Excludes items with prices still to be confirmed.', confirmation: 'Availability, final packed weight, delivery and payment are confirmed directly with Stofpad Biltong.', whatsapp: 'Confirm order on WhatsApp (demo)', review: 'Review WhatsApp message',
    simple: 'Good food. Simple ordering.', step1: '01 / CHOOSE', step1Title: 'Find your favourite.', step1Body: 'Choose your products, weights and preparation options.', step2: '02 / REVIEW', step2Title: 'Put your order together.', step2Body: 'Review your selections and add courier delivery if needed.', step3: '03 / CHAT', step3Title: 'Say it on WhatsApp.', step3Body: 'Send your order to Stofpad Biltong to confirm availability, final pricing and payment.', credit: 'Made with care, by Waldo.', skip: 'Skip to products',
  },
  af: {
    specialKicker: 'NOG IETS LEKKERS', specialHeading: 'Dié week se aanbiedinge.', specialNote: 'Voorbeeldaanbiedinge — pryse, pakgroottes en datums moet nog bevestig word.', specialBadge: 'VOORBEELDAANBOD · MOET BEVESTIG WORD', specialEnquire: 'Doen navraag op WhatsApp ↗', specialMessage: 'Hallo Stofpad Biltong! Ek wil graag oor hierdie voorbeeldaanbod navraag doen:', specialConfirm: 'Bevestig asseblief die aanbodprys, pakgrootte, geldigheidsdatums en beskikbaarheid.',
    nav: 'Hoofnavigasie', products: 'Ons produkte', how: 'Hoe om te bestel', order: 'Jou bestelling',
    eyebrow: 'GROOT SMAAK. SONDER MOEITE.', hero: 'Tyd vir lekker biltong.', intro: 'Iets vir die pad. Iets om te deel. Kies jou gunstelinge en reël die res met Stofpad Biltong op WhatsApp.', browse: 'Verken die produkte ↗', note: 'Kyk hier. Bestel by ’n regte mens.',
    good: 'DIE LEKKER GOED', catalogue: 'Ons biltong & produkte.', catalogueIntro: 'Kies jou gewig en voorbereiding. Voeg jou gunstelinge by een bestelling.', allCount: 'produkte', filter: 'Filter produkte volgens kategorie', swipe: 'Vee om te blaai →', size: 'Gewig / pakgrootte', preparation: 'Voorbereiding', add: 'Voeg by bestelling', pending: 'Prys moet bevestig word', estimate: 'Geskatte prys', added: 'By jou bestelling gevoeg.', limit: 'Jy kan tot 99 van dieselfde keuse byvoeg.',
    orderHeading: 'Jou gunstelinge, saam.', empty: 'Jou bestelling is leeg. Kies iets lekkers uit die katalogus.', remove: 'Verwyder', quantity: 'Hoeveelheid', courier: 'Voeg The Courier Guy-aflewering by — R175', deliveryNote: 'Stofpad Biltong sal koerierbeskikbaarheid en die finale afleweringskoste bevestig.', total: 'Geskatte totaal', known: 'Bekende subtotaal', excludes: 'Sluit produkte uit waarvan pryse nog bevestig moet word.', confirmation: 'Reël beskikbaarheid, finale gewig, aflewering en betaling direk met Stofpad Biltong.', whatsapp: 'Bevestig bestelling op WhatsApp (demo)', review: 'Hersien WhatsApp-boodskap',
    simple: 'Lekker kos. Maklik bestel.', step1: '01 / KIES', step1Title: 'Vind jou gunsteling.', step1Body: 'Kies jou produkte, gewigte en voorbereidingsopsies.', step2: '02 / HERSIEN', step2Title: 'Stel jou bestelling saam.', step2Body: 'Hersien jou keuses en voeg koerieraflewering by indien nodig.', step3: '03 / GESELS', step3Title: 'Sê dit op WhatsApp.', step3Body: 'Stuur jou bestelling aan Stofpad Biltong om beskikbaarheid, finale pryse en betaling te bevestig.', credit: 'Met sorg gemaak, deur Waldo.', skip: 'Gaan na produkte',
  },
};
